
"""
Script de Migração Manual para preparar o banco para o APK
Adiciona suporte a Geolocalização e Solicitações de Torres.
FORÇA O USO DO POSTGRESQL.
"""
import asyncio
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

# URL Definitiva do PostgreSQL (Hardcoded para garantir Migração)
# Em produção viria de variável de ambiente, mas aqui queremos garantir que o script rode no banco certo.
DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost/monitor"

async def update_database():
    print(f"🔄 Conectando ao PostgreSQL em: {DATABASE_URL}")
    
    engine = create_async_engine(DATABASE_URL, echo=True)
    
    async with engine.begin() as conn:
        # 1. Atualizar Tabela TOWERS (Latitude/Longitude)
        print("🗺️ Adicionando colunas de GEO em Towers...")
        try:
            await conn.execute(text("ALTER TABLE towers ADD COLUMN IF NOT EXISTS latitude FLOAT;"))
            await conn.execute(text("ALTER TABLE towers ADD COLUMN IF NOT EXISTS longitude FLOAT;"))
        except Exception as e:
            print(f"⚠️ Erro ao alterar towers (pode já existir): {e}")

        # 2. Atualizar Tabela EQUIPMENTS (Clientes/Paineis)
        print("📡 Adicionando colunas de Clientes em Equipments...")
        try:
            await conn.execute(text("ALTER TABLE equipments ADD COLUMN IF NOT EXISTS is_panel BOOLEAN DEFAULT FALSE;"))
            await conn.execute(text("ALTER TABLE equipments ADD COLUMN IF NOT EXISTS associated_clients INTEGER DEFAULT 0;"))
        except Exception as e:
            print(f"⚠️ Erro ao equipamentos: {e}")

        # 3. Criar Tabela TOWER_REQUESTS
        # Removido SERIAL -> GENERATED BY DEFAULT AS IDENTITY (Padrão SQL moderno) 
        # ou Serial funciona no Postgres, mas vamos simplificar.
        print("📝 Criando tabela de Solicitações (Tower Requests)...")
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS tower_requests (
            id SERIAL PRIMARY KEY,
            name VARCHAR,
            ip VARCHAR,
            latitude FLOAT,
            longitude FLOAT,
            requested_by VARCHAR,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
            status VARCHAR DEFAULT 'pending'
        );
        """
        try:
            await conn.execute(text(create_table_sql))
            await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_tower_requests_id ON tower_requests (id);"))
        except Exception as e:
            print(f"⚠️ Erro ao criar tower_requests: {e}")

    print("✅ Atualização do PostgreSQL concluída!")
    await engine.dispose()

if __name__ == "__main__":
    asyncio.run(update_database())
