import sys
import os
import asyncio
from sqlalchemy import text
from datetime import datetime

# Adicionar raiz ao path
sys.path.append(os.getcwd())

from backend.app.database import engine

async def migrar_particionamento():
    print("=======================================================")
    print("MIGRAÇÃO DE BANCO DE DADOS: PARTICIONAMENTO (PostgreSQL)")
    print("=======================================================")
    print("ATENÇÃO: Este script irá reestruturar a tabela 'ping_logs'.")
    print("Recomendado apenas se você tem > 5 Milhões de registros.")
    print("Certifique-se de ter um backup completo antes de continuar!")
    print("=======================================================")
    
    confirm = input("Digite 'MIGRAR' para continuar: ")
    if confirm != "MIGRAR":
        print("Operação cancelada.")
        return

    async with engine.begin() as conn:
        print("[1/5] Verificando banco de dados...")
        
        # Verificar se já é particionada
        res = await conn.execute(text("SELECT 1 FROM pg_partitioned_table WHERE partrelid = 'ping_logs'::regclass"))
        if res.scalar():
            print("A tabela 'ping_logs' JÁ É particionada. Nada a fazer.")
            return

        # Contar registros
        print("[2/5] Contando registros atuais (pode demorar)...")
        res = await conn.execute(text("SELECT COUNT(*) FROM ping_logs"))
        count = res.scalar()
        print(f"Total de registros: {count}")
        
        if count < 100000:
            print("[INFO] Você tem poucos registros. Particionamento pode ser prematuro.")
            c2 = input("Deseja continuar mesmo assim? (s/n): ")
            if c2.lower() != 's': return

        # Iniciar Migração
        print("[3/5] Renomeando tabela antiga para 'ping_logs_old'...")
        await conn.execute(text("ALTER TABLE ping_logs RENAME TO ping_logs_old"))
        
        # Remover índices da tabela antiga para não conflitar nomes (opcional, mas bom)
        # await conn.execute(text("DROP INDEX IF EXISTS idx_ping_logs_timestamp"))

        print("[4/5] Criando nova tabela Mestre Particionada...")
        # Recria a estrutura idêntica à original
        await conn.execute(text("""
            CREATE TABLE ping_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                target_id INTEGER, -- Adapte conforme seu model (equipment_id ou tower_id?)
                device_type VARCHAR(20),
                device_id INTEGER,
                latency_ms INTEGER,
                status BOOLEAN,
                timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
            ) PARTITION BY RANGE (timestamp);
        """))
        
        # Criar parições para o ano atual e próximo
        year = datetime.now().year
        for y in [year, year + 1]:
            for m in range(1, 13):
                part_name = f"ping_logs_{y}_{m:02d}"
                start_date = f"{y}-{m:02d}-01"
                
                # Calcular end_date
                if m == 12:
                    end_date = f"{y+1}-01-01"
                else:
                    end_date = f"{y}-{m+1:02d}-01"
                
                sql = f"""
                    CREATE TABLE IF NOT EXISTS {part_name} PARTITION OF ping_logs
                    FOR VALUES FROM ('{start_date}') TO ('{end_date}');
                """
                await conn.execute(text(sql))
                print(f"  -> Criada partição: {part_name}")

        # Criar índices na tabela mestre
        print("[INFO] Criando índices globais...")
        await conn.execute(text("CREATE INDEX idx_ping_logs_device ON ping_logs(device_type, device_id)"))
        await conn.execute(text("CREATE INDEX idx_ping_logs_timestamp ON ping_logs USING BRIN(timestamp)"))

        print("[5/5] Migração de dados...")
        print("ATENÇÃO: A tabela nova está VAZIA. A tabela antiga é 'ping_logs_old'.")
        print("Os dados antigos NÃO serão migrados automaticamente por este script para evitar timeout.")
        print("Para migrar dados antigos, rode:")
        print("  INSERT INTO ping_logs SELECT * FROM ping_logs_old;")
        print("(Faça isso em lotes pequenos se tiver milhões de linhas)")
        
        print("\nSUCESSO! O sistema agora gravará novos dados na estrutura particionada.")

if __name__ == "__main__":
    if sys.platform == 'win32':
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(migrar_particionamento())
